### PR TITLE
fix: bypass if not a class

### PR DESCRIPTION
**Pull request by ponces**

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Is this tested? It looks like this will never return due to className never having an extension

**Comment by tillnelown** [comment]
I gave it a try, returns java.lang.ClassNotFoundException: META-INF like without the patch.

**Comment by ponces** [comment]
It was tested in terms of compilation (which not even worked before this)
I'm currently checking the binary produced...

**Comment by oSumAtrIX** [comment]
the patcher compiles already, see the workflow and a commit has already been done locally fixing the related issue anyways.

**Comment by ponces** [comment]
Next time, please make sure sources are always buildable.
Having broken sources and even generating packages with them doesn't make sense :(

**Comment by oSumAtrIX** [comment]
The sources are buildable as already mentioned in the comment before. This is the ˋdevˋ branch and code is bound to break.

**Pull request closed without merging**
