### PR TITLE
feat: decode resources only when necessary

### PR DESCRIPTION
**Pull request by bogadana**
TODO: 
- First decode resources then run patches

### CODE REVIEW

**Comment by bogadana** [comment]
Implements https://github.com/revanced/revanced-patcher/issues/76

**Review by Sculas — APPROVED** [review]

**Review by oSumAtrIX — CHANGES_REQUESTED** [review]
The current implementation will run the patches and when a resource patch is ran, decode the resources. This will look like the patch takes long to run the patch also furthermore breaking the single responsibility principle of the method. Instead, before running the patches, check, a resource patch has been added and decode resources.

**Comment by bogadana** [comment]
> This will look like the patch takes long to run the patch

no as an appropriate log message is printed

> before running the patches, check, a resource patch has been added and decode resources.

tell me how to do this without an instance

**Comment by oSumAtrIX** [comment]
> no as an appropriate log message is printed

While running the patches this would be random.

**Comment by bogadana** [comment]
resource patch -> resources need to be decoded
dont see how thats random

**Comment by oSumAtrIX** [comment]
> While running the patches this would be random.

This is why.

**Comment by bogadana** [comment]
Things should always be done as late as possible its not random at all

**Comment by oSumAtrIX** [comment]
While running the patches it doesn't make sense to decode the resources at the same time. Running the patches is one thing, decoding the resources a different. Doing the latter while the patches run is random. Please decode the resources before running the patches by checking if a resource patch has been supplied.

**Comment by bogadana** [comment]
then answer my other question or ditch reflection already

**Comment by oSumAtrIX** [comment]
I have answered your question in the previous message why it is random and reflection will be ditched when annotations are ditched. Please apply the requested changes.

**Pull request closed without merging**
